### ISSUE TITLE
self contained folder?

### ISSUE THREAD

**Issue by gherkins** [nerdpress-org/docker-sf3#25]
couldn't we move all files to ./docker having everything in one subfolder?

could be used as a git submodule in projects that way..

**Comment by ivoba** [comment]
not sure if this works with docker-compose. did you try?

this would have makes install much easier, though.

i am also not sure if using this as a submodule makes sense.
i rather see this project as a starting point, imo its very likely that you will change things because you maybe like to add redis or remove the database.
what i almost always do is rename the container to have unique per project named container.
would pulling in changes on top of your changes work?

one could also use a generator apporach, like yeoman, with console prompts like "Name your project?", "Choose your DB" and so on...

**Comment by gherkins** [comment]
you're right. the config will be most likely changed.

There seems to be no problem with mounting `..` instead of `.` in the docker-compose.
That would be pretty much the only change, right?

**Comment by ivoba** [comment]
ok lets move it.
and leave it up to the user how he manages docker inside the project.

having it inside a folder makes it possible to use it as a submodule from a users repo, just copy it or put it on gitignore because the rest of the team is not using docker...

**Comment by gherkins** [comment]
Actually we would really just need to change the mount point from `.` to `..`.

You could then just copy/clone anything into your symfony project...
